// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnivaliMapas.Api.DbContexts;

#nullable disable

namespace UnivaliMapas.Migrations
{
    [DbContext(typeof(UnivaliContext))]
    partial class UnivaliContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnivaliMapas.Api.Entities.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaId"));

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            Number = 101
                        },
                        new
                        {
                            SalaId = 2,
                            Number = 102
                        },
                        new
                        {
                            SalaId = 3,
                            Number = 103
                        },
                        new
                        {
                            SalaId = 4,
                            Number = 104
                        },
                        new
                        {
                            SalaId = 5,
                            Number = 105
                        },
                        new
                        {
                            SalaId = 6,
                            Number = 106
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
